# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc5ba53e5c8825aed1dbd46efa06741308b1d4edfb7eb8d6645caa705d5cd25bcdc71ef8cd50a2ac7560fb75292e53f48b1df538afffbec514656c54f66b2743

test:
  secret_key_base: 7b5efbc470e39c367e7d55876f463972911b04b62277d56d1225541d1456adcf744bd794a5123f4fceaf11fc5e1a37b847528f0122ffa20a077a574b76e501e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
